// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uynrwxihykgojihgfrej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5bnJ3eGloeWtnb2ppaGdmcmVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDQ4MzcsImV4cCI6MjA2NTQ4MDgzN30.ZDndkJCkalskSyxHJYJWyCOCluLyXxGGnKFf3PGnwHw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);